SOURCE := main.cpp ClapTrap.cpp ScavTrap.cpp

NAME := serena_my_love

all: $(NAME)

$(NAME): $(SOURCE)
	c++ -Wall -Wextra -Werror -std=c++98 $(SOURCE) -o $(NAME)

clean:

fclean: clean
	rm -f $(NAME)

re: fclean all
